export const TOGGLE_RATIO_PANEL = 'TOGGLE_RATIO_PANEL';
export const CHANGE_WIDGET_HEAD_CURRENCY = 'CHANGE_WIDGET_HEAD_CURRENCY';
export const CHANGE_RATIO_TABLE_CURRENCIES = 'CHANGE_RATIO_TABLE_CURRENCIES';
export const CHANGE_RATIO_PANEL_CURRENCIES = 'CHANGE_RATIO_PANEL_CURRENCIES';
